In [1]:
import pandas as pd
import numpy as np

In [58]:
# Load  data
dataset = pd.read_csv('data/MNT.csv')
dataset.head()

,sexe,age,activité,fumeur,alcool,fruits,légumes,activitéphysiques,trajets,maladiefamille,nommaladie,sport
0,homme,37,Employé(e) de l’Etat,Non,Non,0,3,5,5,oui,Asm,Non
1,homme,37,Employé(e) de l’Etat,oui,Non,3,5,3,3,Non,NaN,oui
2,femme,64,chomeur(se),Non,Non,5,5,5,4,oui,Diabète,Non
3,homme,44,Employé(e) dans le privé,oui,Non,3,5,1,3,Non,NaN,Non
4,homme,25,étudiant,Non,Non,2,4,2,3,Non,NaN,Non

In [48]:
for column in dataset.columns:
     modalites_counts = dataset[column].value_counts()
     print(f"Nombre d'occurrences pour la colonne {column} :\n{modalites_counts}\n")

Nombre d'occurrences pour la colonne sexe :
homme    59
femme    47
Name: sexe, dtype: int64

Nombre d'occurrences pour la colonne age               :
19    20
21    14
18    10
20    10
26     5
23     5
27     4
37     4
33     3
35     3
22     3
25     3
30     3
32     3
38     2
28     2
24     2
29     2
31     1
48     1
64     1
34     1
56     1
44     1
45     1
49     1
Name: age              , dtype: int64

Nombre d'occurrences pour la colonne activité                            :
étudiant                    68
Employé(e) de l’Etat        22
Employé(e) dans le privé    11
chomeur(se)                  5
Name: activité                           , dtype: int64

Nombre d'occurrences pour la colonne fumeur :
Non    100
oui      6
Name: fumeur, dtype: int64

Nombre d'occurrences pour la colonne alcool                                                                 :
Non    99
oui     7
Name: alcool                                                                , dtype: int64

Nombre d'occurrences pour la colonne fruits :
3    35
5    31
2    17
4    16
1     5
0     2
Name: fruits, dtype: int64

Nombre d'occurrences pour la colonne  légumes :
5    52
4    21
3    19
2    13
1     1
Name:  légumes, dtype: int64

Nombre d'occurrences pour la colonne activitéphysiques :
0    36
1    22
2    21
3    11
5    10
4     6
Name: activitéphysiques, dtype: int64

Nombre d'occurrences pour la colonne trajets :
5    35
2    18
1    17
0    15
3    13
4     8
Name: trajets, dtype: int64

Nombre d'occurrences pour la colonne maladiefamille :
oui    74
Non    32
Name: maladiefamille, dtype: int64

Nombre d'occurrences pour la colonne nommaladie :
diabete                           29
la tension(HTA)                   19
asthmatique                        4
La tension                         2
Diabète                            2
Hta                                1
les trois                          1
Diabète, tension, ...              1
les 3                              1
Diabete et hta                     1
Diabete rension...                 1
Asm                                1
mon père                           1
diabétique et asmatique            1
la tension,Insuffisance rénale     1
Diabète.. la tention               1
HTA                                1
Diabète                            1
القلب                              1
Maladies cardiaques                1
Name: nommaladie, dtype: int64

Nombre d'occurrences pour la colonne sport :
Non     88
oui     12
Oui      4
Oui      2
Name: sport, dtype: int64

In [59]:
# Define a function to assign age intervals
def assign_interval(age):
        if 18 <= age <= 20:
            return "18-20"
        elif 20 < age <= 30:
            return "20-30"
        elif 30 < age <= 40:
            return "30-40"
        else:
            return "plus de 40"

    # Apply the function to create a new 'intervalles' column based on age intervals
dataset['age'] = dataset['age'].apply(assign_interval)
   
# Mapping dictionary for standardizing disease names
disease_mapping = {
    'diabete': 'Diabete',
    'HTA': 'Tension(HTA)',
    'Asm': 'Asthme',
    'La tension ': 'Tension(HTA)',
    'Diabète': 'diabete',
    'القلب' : 'Tension(HTA)',
    'la tension(HTA)':'Tension(HTA)',
    'diabete' :'diabete',
    'la tension(HTA)' :'Tension(HTA)',

}

# Apply mapping for '25.si oui c'est quoi la maladies?' column
dataset['nommaladie'] = dataset['nommaladie'].map(disease_mapping)

# Check the result
for column in dataset.columns:
    modalities_counts = dataset[column].value_counts()
    print(f"Nombre d'occurrences pour la colonne {column} :\n{modalities_counts}\n")

Nombre d'occurrences pour la colonne sexe :
homme    59
femme    47
Name: sexe, dtype: int64

Nombre d'occurrences pour la colonne age :
20-30         43
18-20         40
30-40         17
plus de 40     6
Name: age, dtype: int64

Nombre d'occurrences pour la colonne activité :
étudiant                    68
Employé(e) de l’Etat        22
Employé(e) dans le privé    11
chomeur(se)                  5
Name: activité, dtype: int64

Nombre d'occurrences pour la colonne fumeur :
Non    100
oui      6
Name: fumeur, dtype: int64

Nombre d'occurrences pour la colonne alcool :
Non    99
oui     7
Name: alcool, dtype: int64

Nombre d'occurrences pour la colonne fruits :
3    35
5    31
2    17
4    16
1     5
0     2
Name: fruits, dtype: int64

Nombre d'occurrences pour la colonne  légumes :
5    52
4    21
3    19
2    13
1     1
Name:  légumes, dtype: int64

Nombre d'occurrences pour la colonne activitéphysiques :
0    36
1    22
2    21
3    11
5    10
4     6
Name: activitéphysiques, dtype: int64

Nombre d'occurrences pour la colonne trajets :
5    35
2    18
1    17
0    15
3    13
4     8
Name: trajets, dtype: int64

Nombre d'occurrences pour la colonne maladiefamille :
oui    74
Non    32
Name: maladiefamille, dtype: int64

Nombre d'occurrences pour la colonne nommaladie :
diabete         31
Tension(HTA)    26
Asthme           7
Name: nommaladie, dtype: int64

Nombre d'occurrences pour la colonne sport :
Non     88
oui     16
oui      2
Name: sport, dtype: int64

In [60]:

# Check if there are any remaining NaN values
for column in dataset.columns:
    modalities_counts = dataset[column].value_counts()
    print(f"Nombre d'occurrences pour la colonne {column} :\n{modalities_counts}\n")
dataset.to_csv("data/ready_MNT.csv", index=False)

Nombre d'occurrences pour la colonne sexe :
homme    59
femme    47
Name: sexe, dtype: int64

Nombre d'occurrences pour la colonne age :
20-30         43
18-20         40
30-40         17
plus de 40     6
Name: age, dtype: int64

Nombre d'occurrences pour la colonne activité :
étudiant                    68
Employé(e) de l’Etat        22
Employé(e) dans le privé    11
chomeur(se)                  5
Name: activité, dtype: int64

Nombre d'occurrences pour la colonne fumeur :
Non    100
oui      6
Name: fumeur, dtype: int64

Nombre d'occurrences pour la colonne alcool :
Non    99
oui     7
Name: alcool, dtype: int64

Nombre d'occurrences pour la colonne fruits :
3    35
5    31
2    17
4    16
1     5
0     2
Name: fruits, dtype: int64

Nombre d'occurrences pour la colonne  légumes :
5    52
4    21
3    19
2    13
1     1
Name:  légumes, dtype: int64

Nombre d'occurrences pour la colonne activitéphysiques :
0    36
1    22
2    21
3    11
5    10
4     6
Name: activitéphysiques, dtype: int64

Nombre d'occurrences pour la colonne trajets :
5    35
2    18
1    17
0    15
3    13
4     8
Name: trajets, dtype: int64

Nombre d'occurrences pour la colonne maladiefamille :
oui    74
Non    32
Name: maladiefamille, dtype: int64

Nombre d'occurrences pour la colonne nommaladie :
diabete         31
Tension(HTA)    26
Asthme           7
Name: nommaladie, dtype: int64

Nombre d'occurrences pour la colonne sport :
Non     88
oui     16
oui      2
Name: sport, dtype: int64

In [2]:
import pandas as pd

# Load the CSV data into a DataFrame
df = pd.read_csv('ready_MNT.csv')  # Replace 'your_data.csv' with the actual path to your CSV file

# Create a new DataFrame for each unique value in 'nommaladie'
for disease in df['nommaladie'].unique():
    # Filter the data for the specific disease
    disease_df = df[df['nommaladie'] == disease]

    # Create summary statistics based on 'age', 'sexe', and 'activitéphysiques'
    summary_stats = disease_df.groupby(['age', 'sexe', 'sport']).size().reset_index(name='count')

    # Print the summary statistics for the current disease
    print(f"{disease}:\n")
    print(summary_stats)
    print("\n" + "="*50 + "\n")

    # Save the summary statistics to a CSV file
    summary_stats.to_csv(f'{disease}.csv', index=False)

Asthme:

     age   sexe sport  count
0  18-20  femme   Non      1
1  18-20  femme   oui      1
2  18-20  homme   Non      1
3  20-30  femme   Non      1
4  20-30  femme   oui      1
5  20-30  homme   Non      1
6  30-40  homme   Non      1

==================================================

nan:

Empty DataFrame
Columns: [age, sexe, sport, count]
Index: []

==================================================

diabete:

          age   sexe sport  count
0       18-20  femme   Non      9
1       18-20  femme   oui      1
2       18-20  homme   Non      4
3       18-20  homme   oui      1
4       20-30  femme   Non      5
5       20-30  homme   Non      6
6       30-40  femme   Non      2
7       30-40  homme   Non      1
8  plus de 40  femme   Non      1
9  plus de 40  homme   Non      1

==================================================

Tension(HTA):

     age   sexe sport  count
0  18-20  femme   Non      2
1  18-20  femme   oui      1
2  18-20  homme   Non      7
3  20-30  femme   Non      8
4  20-30  femme   oui      1
5  20-30  homme   Non      2
6  20-30  homme   oui      1
7  30-40  homme   Non      1
8  30-40  homme   oui      3

==================================================

In [ ]:
import pandas as pd

# Read the input CSV file
input_file = "data/ready_MNT.csv"  # Replace with your actual file path
data = pd.read_csv(input_file)

# Convert the "age" column to numeric values using the lower bound of each range
data["age"] = data["age"].str.extract('(\d+)-').astype(float)

# Define age groups
age_groups = {
    "18-20": [18, 19],
    "20-30": [20, 29],
    "30-40": [30, 39],
    "plus de 40": [40, 100]  # You can adjust this range accordingly
}

# Get unique diseases from the data
unique_diseases = data["nommaladie"].unique()

# Iterate through each disease
for disease in unique_diseases:
    # Initialize the output DataFrame
    output_data = pd.DataFrame(columns=["score", "Femme(Sport)", "Femme(NonSport)", "Homme(Sport)", "Homme(NonSport)"])

    # Iterate through each age group
    for age_group, age_range in age_groups.items():
        # Filter data for the current disease and age group
        data_age_group = data[(data["nommaladie"] == disease) & (data["age"].notnull()) & (data["age"] >= age_range[0]) & (data["age"] <= age_range[1])]

        # Calculate scores based on the number of rows for the current age group
        femme_sport = len(data_age_group[(data_age_group["sexe"] == "femme") & (data_age_group["sport"] == "oui")])
        femme_nonsport = len(data_age_group[(data_age_group["sexe"] == "femme") & (data_age_group["sport"] == "Non")])
        homme_sport = len(data_age_group[(data_age_group["sexe"] == "homme") & (data_age_group["sport"] == "oui")])
        homme_nonsport = len(data_age_group[(data_age_group["sexe"] == "homme") & (data_age_group["sport"] == "Non")])

        # Append the row to the output DataFrame
        output_data = output_data.append({
            "score": age_group,
            "Femme(Sport)": femme_sport,
            "Femme(NonSport)": femme_nonsport,
            "Homme(Sport)": homme_sport,
            "Homme(NonSport)": homme_nonsport
        }, ignore_index=True)

    # Save the output DataFrame to a CSV file for the current disease
    output_file = f"data/{disease}_file.csv"
    output_data.to_csv(output_file, index=False)

In [1]:
import pandas as pd

# Read the input CSV file
input_file = "data/ready_MNT.csv"  # Replace with your actual file path
data = pd.read_csv(input_file)

# Convert the "age" column to numeric values using the lower bound of each range
data["age"] = data["age"].str.extract('(\d+)-').astype(float)

# Define age groups
age_groups = {
    "18-20": [18, 19],
    "20-30": [20, 29],
    "30-40": [30, 39],
    "plus de 40": [40, 100]  # You can adjust this range accordingly
}

# Get unique diseases from the data
unique_diseases = data["nommaladie"].unique()

# Iterate through each disease
for disease in unique_diseases:
    # Initialize the output DataFrame
    output_data = pd.DataFrame(columns=["score", "Femme(Oui)", "Femme(Non)", "Homme(Oui)", "Homme(Non)"])

    # Iterate through each age group
    for age_group, age_range in age_groups.items():
        # Filter data for the current disease and age group
        data_age_group = data[(data["nommaladie"] == disease) & (data["age"].notnull()) & (data["age"] >= age_range[0]) & (data["age"] <= age_range[1])]

        # Calculate scores based on the number of rows for the current age group
        femme_oui = len(data_age_group[(data_age_group["sexe"] == "femme") & (data_age_group["fumeur"] == "oui")])
        femme_non = len(data_age_group[(data_age_group["sexe"] == "femme") & (data_age_group["fumeur"] == "Non")])
        homme_oui = len(data_age_group[(data_age_group["sexe"] == "homme") & (data_age_group["fumeur"] == "oui")])
        homme_non = len(data_age_group[(data_age_group["sexe"] == "homme") & (data_age_group["fumeur"] == "Non")])

        # Append the row to the output DataFrame
        output_data = output_data.append({
            "score": age_group,
            "Femme(Oui)": femme_oui,
            "Femme(Non)": femme_non,
            "Homme(Oui)": homme_oui,
            "Homme(Non)": homme_non
        }, ignore_index=True)

    # Save the output DataFrame to a CSV file for the current disease
    output_file = f"data/{disease}_file2.csv"
    output_data.to_csv(output_file, index=False)

C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({
C:\Users\26\AppData\Local\Temp\ipykernel_4092\3914197165.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  output_data = output_data.append({